### ISSUE TITLE
KeyError raised when generating index files on full uranus occ bundles 

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-data-projects#75]
When trying to generate index files on full uranus occ bundles, it will raise a KeyError if `--sort-by pds:filename` is appened at the end of the command. If the `--sort-by` argument is removed then it will run without an error.
- venv setup based on python 3.9, running on `main` branch, and here are the versions of packages for reference:
```
(venv) yjchang@staging:~/rms-data-projects/indextools$ pip freeze
lxml==4.9.3
numpy==1.26.4
pandas==2.1.4
python-dateutil==2.9.0.post0
pytz==2024.1
six==1.16.0
tzdata==2024.1
(venv) yjchang@staging:~/rms-data-projects/indextools$ git branch
* main
(venv) yjchang@staging:~/rms-data-projects/indextools$ python --version
Python 3.9.18
```
- Here is the error log with the command used:
```
(venv) yjchang@staging:~/rms-data-projects/indextools$ python pds4_create_xml_index.py /volumes/pdsdata-raid45/pds4-holdings/bundles/uranus_occs_earthbased "uranus_occ_u*/data/rings/u*_*m.xml" --output-file uranus_rings_occultations_index.tab --sort-by pds:filename
Traceback (most recent call last):
  File "/home/yjchang/rms-data-projects/indextools/pds4_create_xml_index.py", line 299, in <module>
    main()
  File "/home/yjchang/rms-data-projects/indextools/pds4_create_xml_index.py", line 295, in main
    write_results_to_csv(all_results, args, output_path)
  File "/home/yjchang/rms-data-projects/indextools/pds4_create_xml_index.py", line 179, in write_results_to_csv
    df.sort_values(by=args.sort_by, inplace=True)
  File "/home/yjchang/rms-data-projects/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 6944, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
  File "/home/yjchang/rms-data-projects/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'pds:filename'
(venv) yjchang@staging:~/rms-data-projects/indextools$ python pds4_create_xml_index.py /volumes/pdsdata-raid45/pds4-holdings/bundles/uranus_occs_earthbased "uranus_occ_u*/data/rings/u*_*m.xml" --output-file uranus_rings_occultations_index.csv --sort-by pds:filename
Traceback (most recent call last):
  File "/home/yjchang/rms-data-projects/indextools/pds4_create_xml_index.py", line 299, in <module>
    main()
  File "/home/yjchang/rms-data-projects/indextools/pds4_create_xml_index.py", line 295, in main
    write_results_to_csv(all_results, args, output_path)
  File "/home/yjchang/rms-data-projects/indextools/pds4_create_xml_index.py", line 179, in write_results_to_csv
    df.sort_values(by=args.sort_by, inplace=True)
  File "/home/yjchang/rms-data-projects/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 6944, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
  File "/home/yjchang/rms-data-projects/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'pds:filename'
(venv) yjchang@staging:~/rms-data-projects/indextools$ 
(venv) yjchang@staging:~/rms-data-projects/indextools$ python pds4_create_xml_index.py /volumes/pdsdata-raid45/pds4-holdings/bundles/uranus_occs_earthbased "uranus_occ_u*/data/rings/u*_*m.xml" --output-file uranus_rings_occultations_index.csv 
(venv) yjchang@staging:~/rms-data-projects/indextools$ python pds4_create_xml_index.py /volumes/pdsdata-raid45/pds4-holdings/bundles/uranus_occs_earthbased "uranus_occ_u*/data/rings/u*_*m.xml" --output-file uranus_rings_occultations_index.tab 
(venv) yjchang@staging:~/rms-data-projects/indextools$
```

**Comment by esimpsons3ti** [comment]
@juzen2003  The `filename` column is not automatically generated for the index files. You need to use `--extra-file-info` to add that column in specifically. This is what is causing the `KeyError`: it can't sort by what isn't there. Make the following changes to your command:

Add `--extra-file-info filename`

Use `--sort-by filename` instead of `--sort-by pds:filename`

I used a modified version of your original command with these changes, and it worked for me. Let me know if this works for you!

**Comment by juzen2003** [comment]
Thanks, it works perfect after updating the command.

**Comment by matthewtiscareno** [comment]
Would it be good Python practice for this discrepancy in the call to be noticed immediately and to result in a cleaner error so that the user knows how to fix it?

**Comment by rfrenchseti** [comment]
I think in general it's bad form for a program to crash with an exception just because the user gave a bad value on the command line. All such exceptions should be caught and reasonable error messages printed. And all command line options should be validated before use.
